### ISSUE TITLE
Unnötige Typumwandlung

### ISSUE THREAD

**Issue by behrends** [freshPrinceE/VokabelApp#1]
Typumwandlungen können bei `findViewById` weggelassen werden `(FloatingActionButton) findView...`:
https://github.com/freshPrinceE/VokabelApp/blob/9ec108161e888ddf2ea6665309aefc5a9ddf88be/app/src/main/java/com/example/i01002706/vokabelapp/MainActivity.java#L70

**Comment by freshPrinceE** [comment]
Behoben
