### ISSUE TITLE
String-Vergleich sollte equals() verwenden

### ISSUE THREAD

**Issue by behrends** [freshPrinceE/VokabelApp#2]
In Java sollten Strings mit `equals()` verglichen werden (gefunden in Android Studio durch `Analyze > Inspect Code…`)
https://github.com/freshPrinceE/VokabelApp/blob/9ec108161e888ddf2ea6665309aefc5a9ddf88be/app/src/main/java/com/example/i01002706/vokabelapp/NewCard.java#L79

**Comment by freshPrinceE** [comment]
Behoben
