### ISSUE TITLE
ClickListener als anonyme Klasse

### ISSUE THREAD

**Issue by behrends** [freshPrinceE/VokabelApp#4]
Es ist wohl nicht nötig, dass die Activity das Interface `AdapterCategory.ItemClickListener` implementiert:
https://github.com/freshPrinceE/VokabelApp/blob/ab54b4469c9f9c2237524c9de97882b9fd4f919a/app/src/main/java/com/example/i01002706/vokabelapp/MainActivity.java#L22

Dies lässt sich auch ohne solch ein Interface umsetzen, und zwar könnte diese Zeile

https://github.com/freshPrinceE/VokabelApp/blob/ab54b4469c9f9c2237524c9de97882b9fd4f919a/app/src/main/java/com/example/i01002706/vokabelapp/MainActivity.java#L66

mit einer anonymen inneren Klasse wie folgt geändert werden:

```
adapter.setClickListener(new AdapterCategory.ItemClickListener() {
            @Override
            public void onItemClick(View view, int position) {
                Toast.makeText(MainActivity.this, "You clicked " + adapter.getItem(position).getId() + " on row number " + position, Toast.LENGTH_LONG).show();
                Intent intent = new Intent(MainActivity.this, CardsetActivity.class);
                Bundle b = new Bundle();
                b.putInt("id", adapter.getItem(position).getId());
                intent.putExtras(b);
                startActivity(intent);
            }
        });
```

**Comment by freshPrinceE** [comment]
Umgesetzt
